# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - strapi-quickstart

on:
  push:
    branches:
      - feature/mysql
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_d7c3e9a3c00d44de872adf3744a4c863 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b340fb6988b14594b668cc8c2d834079 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_d7c3e9a3c00d44de872adf3744a4c863 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'strapi-quickstart'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_38ece63444144ae59bef735aa19620a4 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_d7c3e9a3c00d44de872adf3744a4c863 }}/appsvc/staticsite:${{ github.sha }}'