# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - strapi-quickstart

on:
  push:
    branches:
      - feature/mysql
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_536a419d970643b8b6bf0a2c78a442b8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7106868698344e57a9757513c20d15d0 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_536a419d970643b8b6bf0a2c78a442b8 }}/azure-app-service/windows/parkingpage:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'strapi-quickstart'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e9d5c1b84af2494896ab6948e09a0b27 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_536a419d970643b8b6bf0a2c78a442b8 }}/azure-app-service/windows/parkingpage:${{ github.sha }}'